### ISSUE TITLE
Списки категорий и продуктов для команд продуктов не соответствуют действительности 

### ISSUE THREAD

**Issue by ocassio** [ncedu-tlt/console-catalog#12]
Для воспроизведения ошибки необходимо модифицировать список категорий, затем загрузить данные из файла и попытаться добавить продукт.

Ошибка вызвана использованием данного подхода:
```java
private List<Product> products = ProductsRepository.getInstance().get();
private List<Category> categories = CategoriesRepository.getInstance().get();
```

При таком подходе данные получаются от репозитория всего один раз, а дальше живут своей жизнью, т.к. сохранена ссылка на старый список, а при загрузке данных из файла в репозитории создается новый.

**Comment by jegius** [comment]
Как лучше поступить?  реализовать геттеры и сетеры для коллекций и добавить их в логику работы репозиториев, или просто убрать модификатор доступа?

**Comment by jegius** [comment]
Или достаточно перенести создание коллекции непосредственно в метод, не затрагивая поля класса?

**Comment by ocassio** [comment]
Получай списки от репозитория уже в процессе работы команды. Особенно это станет актуально, когда мы перейдем на использование БД.

**Comment by jegius** [comment]
c304688eccad8a417a396639d3c37b211b46317b

Готово! Коллекции перенесены в метод.
