### ISSUE TITLE
Избавится от излишних приватных полей

### ISSUE THREAD

**Issue by ocassio** [ncedu-tlt/console-catalog#13]
Пример:
```java
private List<Product> searchResult;
```

Такие поля используются только в рамках одного вызова execute и могут быть заменены на локальные переменные с пробросом между методами.

**Comment by jegius** [comment]
Лишние поля класса убраны, все переменные перенесены в локальные поля использующих их методов. 906e6206bbd00e1091c340eeed9f9c5e0a9fe63b
