### ISSUE TITLE
Доработка способа удаления продуктов по категории

### ISSUE THREAD

**Issue by ocassio** [ncedu-tlt/console-catalog#9]
Советую видоизменить метод ProductsRepository#remove(List<Product>).
Будет лучше, если он будет принимать на вход идентификатор категории, а логика по поиску соответствующих продуктов будет инкапсулирована в репозитории.
Также вызов этого метода стоит перенести в метод удаления категории в соответствующем репозитории. Таким образом, мы добьемся консистентного поведения системы вне зависимости от того, в каком месте мы решили удалить категорию.

**Comment by jegius** [comment]
Выполнено логика перенесена в репозиторий продуктов, вызов метода удаления продуктов перенесен в репозиторий каталога
0ddec5ce8ea4e2b01fcb1dfaebf982b494247c24
